<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Dytools.VirtualFileSystem.Benchmarks</RootNamespace>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <!-- Release-mode artifacts should be used for accurate benchmark numbers. -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet"                          Version="0.14.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dytools.VirtualFileSystem\Dytools.VirtualFileSystem.csproj" />
  </ItemGroup>

</Project>
