<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Dytools.VirtualFileSystem.Sample</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dytools.VirtualFileSystem\Dytools.VirtualFileSystem.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Profiler.Api" Version="1.4.13" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

</Project>
